apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-api
  labels:
    app: devsecops-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecops-api
  template:
    metadata:
      labels:
        app: devsecops-api
    spec:
      containers:
        - name: devsecops-api
          image: devsecops-api:latest
          ports:
            - containerPort: 5000
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: devsecops-api-service
spec:
  selector:
    app: devsecops-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
